name: sampleproject

on: [push]
jobs:
  setup:
    runs-on: windows-2019
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
  build:
    steps:
      - name: Build Sfagent Binary
        run: |
          echo "hello"
          go build -o hello.exe
          ls
      - name: create a directory for MSI Setup
        run: |
          cd ..
          ls
          mkdir -p windows-msi
          cd windows-msi
        #working-directory: ./temp