name: sampleproject

on: [push]
jobs:
  samplejob:
    runs-on: windows-2019
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Build Sfagent Binary
        run: |
          echo "hello"
          ls
      - name: create a directory
        run: |
          mkdir -p ${{ github.workspace }}\sampledir
          cd sampledir
          touch sampleconfig.yaml
        #working-directory: ./temp