name: sampleproject

on: [push]
jobs:
  release:
    runs-on: windows-2019
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Build Sfagent Binary
        run: |
          echo "hello"
          go build -o hello.exe
          ls "C:\Program Files (x86)"
      - name: create a directory for MSI Setup
        run: |
          mkdir -p ../windows-msi
          cp ./hello.exe ../windows-msi/
          cp ./msi-installer/sample.wxs ../windows-msi
          cd ../windows-msi
          ls
          candle sample.wxs
        #working-directory: ./temp