name: sampleproject

on: [push]
jobs:
  samplejob:
    runs-on: windows-2019
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: create a directory
        run: |
          mkdir GITHUB_WORKSPACE/sampledirectory
          echo ${env:PATH}
          touch config.yaml
        working-directory: ./temp