name: sampleproject

on: [push]
jobs:
  samplejob:
    runs-on: windows-2019
    steps: 
      - name: create a directory
        run: |
          mkdir sampledirectory
          echo ${env:PATH}
          touch config.yaml
        working-directory: ./temp